### ISSUE TITLE
Implement QuickMenu feature

### ISSUE THREAD

**Issue by codeimpl** [triplebanana/triple_banana#928]
This is META issue to implement QuickMenu feature.
To resolve this issue, we should finish the following works:
- [x] Sketch sequence and interfaces (#929)
- [x] Implement initial skeleton codes (#930)
- [ ] Implement QuickMenuContainer (#931)
- [ ] Support Dark Mode (#938)
- [ ] Implement QuickMenuLayout (#932)
- [ ] Implement QuickMenuModel for Top/Bottom/MiddleBar (#933)
- [ ] Implement QuickMenuNormalButton (#934)
- [ ] Implement QuickMenuToggleButton (#935)
- [ ] Implement QuickMenuActionProvider (#936)

**Comment by romandev** [comment]
This was already implemented.
